name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: |
        ./autogen.sh
    - name: make
      run: make
    - name: artifact
      uses: actions/upload-artifact@v4
      with:
        name: ps3xport-linux
        path: ./ps3xport

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v4
    - uses: msys2/setup-msys2@v2
      with:
        install: gcc autotools zlib-devel
    - name: configure
      run: ./autogen.sh
    - name: make
      run: make
    - name: artifact
      uses: actions/upload-artifact@v4
      with:
        name: ps3xport-windows
        path: ./ps3xport.exe
