name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: |
        ./autogen.sh
    - name: make
      run: make
    - name: artifact
      uses: actions/upload-artifact@v4
      with:
        path: ./ps3xport
